name: Build Mod

on:
  push:
    branches: [ 1.20.1-forge-1.0.1-major_version ]
  pull_request:
    branches: [ 1.20.1-forge-1.0.1-major_version ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InfoPlus-Build
          path: build/libs/*.jar
