name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR Artifact (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: InfoPlus-Build
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: InfoPlus-Build
          path: ./build/libs

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
